### ISSUE TITLE
Character Sheet: Attribute Groups

### ISSUE THREAD

**Issue by cameronpenner** [cameronpenner/SoftwareEngineering2#1]
Characters have multiple skills including base skills (Agility, Strength, etc.) and also more specific skills (history, stealth, weapon proficiency) this would show a number of what level that character is for each skill, as well as the name of the skill and posibly a short description.

Points: 2

Epic: https://trello.com/c/UAykuSxX/2-i-want-to-create-and-modify-my-character-sheet

**Comment by ghost** [comment]
cost: 2
priority: high
