### ISSUE TITLE
game master appoint new game master

### ISSUE THREAD

**Issue by cameronpenner** [cameronpenner/SoftwareEngineering2#10]
The game master (leader of the campaign) should be able to select other players (within the campaign) to be the new game master. This will remove them as the group controller, and take away their access to other characters.

Points: 1

Epic: https://trello.com/c/qa1kO16p/22-i-want-game-masters-to-be-able-to-appoint-new-game-masters-for-the-campaign

**Comment by ghost** [comment]
cost: 1
priority: high

**Comment by Dennan** [comment]
Done
