### ISSUE TITLE
Adding players to campaign.

### ISSUE THREAD

**Issue by Nolan-Labelle** [cameronpenner/SoftwareEngineering2#108]
When you click to add a character without opening the dropdown, it locks you out from adding the next one in the list.

Assumption of what is going wrong:
When a Character is removed from the list to be added to the campaign, the list is updated, but the indices are not, resulting in this process:

Add character from index 1,
try to add character that is now in index 1, nothing happens,
try to add character that is now in index 2, adds the character from index 1.

This should work with any combination, such as trying to add character in index 3 and the character in index 2 being added instead.

**Comment by Nolan-Labelle** [comment]
Checked it again, even happens when opening the drop down.

**Comment by Dennan** [comment]
happens because indexes are based on the master character list, which doesn't change even when the drop down list content changes

**Comment by Dennan** [comment]
It doesn't do this anymore
