### ISSUE TITLE
game master access to other character sheets

### ISSUE THREAD

**Issue by cameronpenner** [cameronpenner/SoftwareEngineering2#11]
When the game master views his list of characters, below will be a list of other characters in the campaign (the players characters) The game master will be able to select those characters and edit them as well.

Points: 2

Epic: https://trello.com/c/BEfvIHUm/20-as-a-game-master-i-want-to-be-able-to-manage-different-users-character-sheets

**Comment by ghost** [comment]
cost: 2
priority: high

**Comment by Dennan** [comment]
Closely linked with https://github.com/cameronpenner/SoftwareEngineering2/issues/8#issuecomment-187411326

**Comment by ghost** [comment]
killed

**Comment by Nolan-Labelle** [comment]
Currently has a pull request (#122), but it still has the bug of taking ownership of the character when edited.

**Comment by Nolan-Labelle** [comment]
Currently, gamemaster just needs a way to select them and to fix the bug of taking ownership upon edit.

**Comment by ghost** [comment]
https://github.com/cameronpenner/SoftwareEngineering2/pull/135
