### ISSUE TITLE
back button in character / item / attributes UI

### ISSUE THREAD

**Issue by ghost** [cameronpenner/SoftwareEngineering2#110]
Marker's feedback: 'You need to provide back button in order to navigate between Items and its
attributes.'

**Comment by IrinaAugust** [comment]
@jsloewen, do you mean a button to go from the Item view back to the Character view? To do that, you can just click the item's owner name from the Item view.
Maybe we can make it more obviously clickable because currently it looks like simple text.

**Comment by ghost** [comment]
@IrinaAugust yeah maybe lets make it a button that says something like 'back to (charactername)'

**Comment by IrinaAugust** [comment]
Looks good?  
![untitled](https://cloud.githubusercontent.com/assets/16784872/13836885/e7b999c8-ebd3-11e5-9f84-d036d85e2353.png)

**Comment by IrinaAugust** [comment]
BTW, the item name caption had a similar functionality to the character's name prior to my changes. It may not be obvious that you can rename the item when clicking in its name. I was going to modify/add the style that would change the cursor to 'hand' when you hover over the item name. But that that the exact thing that the character's name caption had at the beginning, and we decided on changing it. 
Any thoughts?
We could make the  item name to be a button but I am not sure if that would look nice.

**Comment by Nolan-Labelle** [comment]
I would say to go with a button for it as well, just would make it look overall more in line with other "clickable" instances.
