### ISSUE TITLE
player can deny changes

### ISSUE THREAD

**Issue by cameronpenner** [cameronpenner/SoftwareEngineering2#12]
The user should be able to choose to accept or decline changes from other players (the game master) When a change is submitted the user will be given a prompt to accept or decline the change.

Points: 2

Epic: https://trello.com/c/PO8AwC4p/19-i-want-to-be-able-to-choose-to-accept-decline-other-user-s-the-game-master-s-changes

**Comment by ghost** [comment]
cost: 5
priority: low

**Comment by ghost** [comment]
not doing this
