### ISSUE TITLE
notifications for changes

### ISSUE THREAD

**Issue by cameronpenner** [cameronpenner/SoftwareEngineering2#13]
The user should be notified when a change is made to his character sheet by someone else. A sound and/or a visual cue (highlight the change) should let the player know something is different now.

Points: 2

Epic :https://trello.com/c/NzDtgJ8f/10-i-want-to-be-notified-when-my-character-sheet-is-changed-by-someone-else-the-game-master

**Comment by ghost** [comment]
cost: 6
priority: medium
