### ISSUE TITLE
Creating multiple chracters with presets

### ISSUE THREAD

**Issue by Nolan-Labelle** [cameronpenner/SoftwareEngineering2#142]
When you create a character with a preset, the next time you go to create a character without reloading the page, the preset should be reset, but it is not.

Steps to reproduce:
1. Click to create a new character
2. Choose a preset
3. Click save
2. Click to create a new character
5. Skip choosing a preset
6. Click save
7. Notice how the preset is still from the previous one, instead of having no preset.

**Comment by IrinaAugust** [comment]
fixed by merge #148
