### ISSUE TITLE
Add bottom padding to Character List

### ISSUE THREAD

**Issue by IrinaAugust** [cameronpenner/SoftwareEngineering2#151]
Right now it looks rather squished 
![presets](https://cloud.githubusercontent.com/assets/16784872/14192979/cdf85986-f766-11e5-8a97-881645c8aae8.png)

I want to add enough padding to accommodate for the dropdown preset menu
![presets2](https://cloud.githubusercontent.com/assets/16784872/14193007/0c56b22c-f767-11e5-921c-e1c99793597d.png)

**Comment by IrinaAugust** [comment]
merged in #152

**Comment by IrinaAugust** [comment]
Add padding in the campaign page

**Comment by Nolan-Labelle** [comment]
Was removed from the characters in the alternate view app, but now has been re-added as well as the one for campaigns.

**Comment by Nolan-Labelle** [comment]
Merged in
