### ISSUE TITLE
Require login

### ISSUE THREAD

**Issue by Dennan** [cameronpenner/SoftwareEngineering2#26]
The user should have to log in before any other actions are performed

**Comment by ghost** [comment]
cost 1
priority medium

**Comment by ghost** [comment]
working on this and refactoring accounts in the same pull request: https://github.com/cameronpenner/SoftwareEngineering2/pull/50

**Comment by ghost** [comment]
done along with accounts change https://github.com/cameronpenner/SoftwareEngineering2/commit/d5eb992b4b67712400435c7df9491f47ab3a7ae7
