### ISSUE TITLE
Character Sheet: quick edit stats

### ISSUE THREAD

**Issue by cameronpenner** [cameronpenner/SoftwareEngineering2#3]
Characters have some stats the change constantly during play such as Health, Money, Fortitude, Will, etc. These traits should be quick to add to and take away from. (+/- buttons next to them as well as the normal text entry input)

Points: 3

Epic: https://trello.com/c/UAykuSxX/2-i-want-to-create-and-modify-character-sheets

**Comment by ghost** [comment]
cost: 3
priority: medium

**Comment by ghost** [comment]
I started playing around a bit on the weekend, figured I would assign myself this because I think I have something that will work

**Comment by ghost** [comment]
see this pull request: https://github.com/cameronpenner/SoftwareEngineering2/pull/48

**Comment by ghost** [comment]
make that this pull request: https://github.com/cameronpenner/SoftwareEngineering2/pull/59

**Comment by ghost** [comment]
Merged into develop
