### ISSUE TITLE
Create profile package for handling user/account stuff

### ISSUE THREAD

**Issue by Dennan** [cameronpenner/SoftwareEngineering2#31]

**Comment by ghost** [comment]
cost 3
priority high

**Comment by ghost** [comment]
working on this and requiring user to log in with the same pull request https://github.com/cameronpenner/SoftwareEngineering2/pull/50

**Comment by ghost** [comment]
see accountsChange merged into develop. https://github.com/cameronpenner/SoftwareEngineering2/commit/d5eb992b4b67712400435c7df9491f47ab3a7ae7
