### ISSUE TITLE
edit other players character sheet

### ISSUE THREAD

**Issue by cameronpenner** [cameronpenner/SoftwareEngineering2#8]
A Game master should have access to his own character sheets as well as the character sheets of other members of the campaign.

We will need #9 done before this can be implemented.

Points: 1

Epic: https://trello.com/c/uK7BS82b/4-i-want-a-game-master-to-be-able-to-update-my-character-sheet

**Comment by ghost** [comment]
cost: 1
priority: high

**Comment by Dennan** [comment]
Unassigning myself for now because I need to cut down the number of stories I have

**Comment by Dennan** [comment]
Closely linked with https://github.com/cameronpenner/SoftwareEngineering2/issues/11

**Comment by ghost** [comment]
not for iter 2

**Comment by cameronpenner** [comment]
duplicate
